version: '3'

services:
  # server:
  #   build: ./server
  #   image: node:10.16.0
  #   ports:
  #     - 8080:8080

  db:
    image: postgres
    container_name: trellio-pg
    restart: always
    env_file:
      - docker.env

    volumes:
      - ./server/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./server/db/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
